# Generated by Django 5.2.6 on 2025-09-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(max_length=100)),
                ('attendance', models.FloatField()),
                ('avg_test_score', models.FloatField()),
                ('attempts', models.IntegerField(default=0, null=True)),
                ('fees_paid', models.FloatField()),
                ('backlogs', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
