# Generated by Django 5.2.6 on 2025-09-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropout_backend', '0003_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
