# Generated by Django 5.2.6 on 2025-09-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropout_backend', '0004_delete_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('institute', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='mentors/')),
            ],
        ),
    ]
