# Generated by Django 5.2.6 on 2025-09-22 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropout_backend', '0006_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='dropout_backend.studentrecord'),
        ),
    ]
