# Generated by Django 5.2.6 on 2025-09-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropout_backend', '0008_alter_studentrecord_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentrecord',
            name='predicted_label',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='prediction_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentrecord',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='prediction',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
